# mrblib/url/curl_options.gen.rb
#
# GENERATED by scripts/gen_curl_options.rb from libcurl 8.21.0-DEV's own
# option docs (deps/curl/docs/libcurl/opts) and the CURLOPT macros in
# include/curl/curl.h. DO NOT EDIT BY HAND -- re-run the generator after
# bumping the curl submodule.
#
# BY_PROTOCOL maps each curl "Protocol:" token to the curl_easy options curl
# documents as applying to it. "All" is every protocol; "TLS" and "TCP" are
# cross-cutting (TLS-capable / TCP-based) -- endpoints.rb decides which scheme
# classes compose which tokens. TYPES gives each option's curl value type so
# the binding can marshal it generically and reject the callback/handle types
# a kwarg can't carry.

class URL
  module CurlOptions
      # 308 options across 19 protocol tokens.
      BY_PROTOCOL = {
        "All" => %i[
          abstract_unix_socket address_scope buffersize closesocketdata closesocketfunction
          connect_only connect_to connecttimeout connecttimeout_ms conv_from_network_function
          conv_from_utf8_function conv_to_network_function crlf curlu debugdata debugfunction
          default_protocol disallow_username_in_url dns_cache_timeout dns_interface
          dns_local_ip4 dns_local_ip6 dns_servers dns_shuffle_addresses dns_use_global_cache
          doh_url errorbuffer forbid_reuse fresh_connect happy_eyeballs_timeout_ms
          haproxy_client_ip haproxyprotocol headerdata httpproxytunnel infilesize
          infilesize_large interface ioctldata ioctlfunction ipresolve localport localportrange
          low_speed_limit low_speed_time max_recv_speed_large max_send_speed_large maxage_conn
          maxconnects maxfilesize maxlifetime_conn netrc netrc_file nobody noprogress noproxy
          nosignal opensocketdata opensocketfunction password path_as_is port pre_proxy
          prereqdata prereqfunction private progressfunction protocols protocols_str proxy
          proxy_service_name proxy_transfer_mode proxyauth proxyheader proxypassword proxyport
          proxytype proxyusername proxyuserpwd quick_exit readdata readfunction resolve
          resolver_start_data resolver_start_function resume_from resume_from_large share
          sockoptdata sockoptfunction socks5_auth socks5_gssapi_nec socks5_gssapi_service
          stderr suppress_connect_headers timeout timeout_ms transfertext unix_socket_path
          upkeep_interval_ms upload upload_buffersize url username userpwd verbose writedata
          writefunction xferinfodata xferinfofunction
        ],
        "FILE" => %i[
          filetime new_directory_perms new_file_perms range timecondition
        ],
        "FTP" => %i[
          accepttimeout_ms append chunk_bgn_function chunk_data chunk_end_function
          customrequest dirlistonly filetime fnmatch_data fnmatch_function ftp_account
          ftp_alternative_to_user ftp_create_missing_dirs ftp_filemethod ftp_skip_pasv_ip
          ftp_ssl_ccc ftp_use_eprt ftp_use_epsv ftp_use_pret ftpport ftpsslauth header
          headerfunction ignore_content_length krblevel maxfilesize_large postquote prequote
          quote range seekdata seekfunction server_response_timeout server_response_timeout_ms
          service_name timecondition use_ssl wildcardmatch
        ],
        "HTTP" => %i[
          accept_encoding altsvc altsvc_ctrl autoreferer aws_sigv4 cookie cookiefile cookiejar
          cookielist cookiesession copypostfields customrequest expect_100_timeout_ms
          failonerror filetime followlocation gssapi_delegation header headerfunction headeropt
          hsts hsts_ctrl hstsreaddata hstsreadfunction hstswritedata hstswritefunction
          http09_allowed http200aliases http_content_decoding http_transfer_decoding
          http_version httpauth httpget httpheader httppost ignore_content_length
          keep_sending_on_error maxfilesize_large maxredirs mime_options mimepost pipewait post
          postfields postfieldsize postfieldsize_large postredir put range redir_protocols
          redir_protocols_str referer request_target seekdata seekfunction service_name
          stream_depends stream_depends_e stream_weight timecondition timevalue timevalue_large
          trailerdata trailerfunction transfer_encoding unrestricted_auth useragent
          xoauth2_bearer
        ],
        "IMAP" => %i[
          customrequest header headerfunction httpheader login_options mime_options mimepost
          sasl_authzid sasl_ir server_response_timeout server_response_timeout_ms service_name
          upload_flags use_ssl xoauth2_bearer
        ],
        "IMAPS" => %i[
          upload_flags
        ],
        "LDAP" => %i[
          login_options service_name xoauth2_bearer
        ],
        "MQTT" => %i[
          copypostfields maxfilesize_large postfields postfieldsize postfieldsize_large
        ],
        "POP3" => %i[
          customrequest dirlistonly header headerfunction login_options server_response_timeout
          server_response_timeout_ms service_name use_ssl xoauth2_bearer
        ],
        "RTSP" => %i[
          copypostfields interleavedata interleavefunction postfieldsize postfieldsize_large
          range rtsp_client_cseq rtsp_request rtsp_server_cseq rtsp_session_id rtsp_stream_uri
          rtsp_transport
        ],
        "SCP" => %i[
          keypasswd new_directory_perms new_file_perms server_response_timeout
          server_response_timeout_ms ssh_auth_types ssh_compression ssh_host_public_key_md5
          ssh_host_public_key_sha256 ssh_hostkeydata ssh_hostkeyfunction ssh_keydata
          ssh_keyfunction ssh_knownhosts ssh_private_keyfile ssh_public_keyfile
        ],
        "SFTP" => %i[
          append dirlistonly filetime keypasswd new_directory_perms new_file_perms postquote
          quote range seekdata seekfunction server_response_timeout server_response_timeout_ms
          ssh_auth_types ssh_compression ssh_host_public_key_md5 ssh_host_public_key_sha256
          ssh_hostkeydata ssh_hostkeyfunction ssh_keydata ssh_keyfunction ssh_knownhosts
          ssh_private_keyfile ssh_public_keyfile
        ],
        "SMB" => %i[
          filetime
        ],
        "SMTP" => %i[
          customrequest header headerfunction httpheader login_options mail_auth mail_from
          mail_rcpt mail_rcpt_allowfails mime_options mimepost sasl_ir server_response_timeout
          server_response_timeout_ms service_name use_ssl xoauth2_bearer
        ],
        "TCP" => %i[
          tcp_fastopen tcp_keepalive tcp_keepcnt tcp_keepidle tcp_keepintvl tcp_nodelay
        ],
        "TELNET" => %i[
          telnetoptions
        ],
        "TFTP" => %i[
          tftp_blksize tftp_no_options
        ],
        "TLS" => %i[
          ca_cache_timeout cainfo cainfo_blob capath certinfo crlfile doh_ssl_verifyhost
          doh_ssl_verifypeer doh_ssl_verifystatus ech egdsocket issuercert issuercert_blob
          keypasswd pinnedpublickey proxy_cainfo proxy_cainfo_blob proxy_capath proxy_crlfile
          proxy_issuercert proxy_issuercert_blob proxy_keypasswd proxy_pinnedpublickey
          proxy_ssl_cipher_list proxy_ssl_options proxy_ssl_verifyhost proxy_ssl_verifypeer
          proxy_sslcert proxy_sslcert_blob proxy_sslcerttype proxy_sslkey proxy_sslkey_blob
          proxy_sslkeytype proxy_sslversion proxy_tls13_ciphers proxy_tlsauth_password
          proxy_tlsauth_type proxy_tlsauth_username random_file ssl_cipher_list ssl_ctx_data
          ssl_ctx_function ssl_ec_curves ssl_enable_alpn ssl_enable_npn ssl_falsestart
          ssl_options ssl_sessionid_cache ssl_signature_algorithms ssl_verifyhost
          ssl_verifypeer ssl_verifystatus sslcert sslcert_blob sslcerttype sslengine
          sslengine_default sslkey sslkey_blob sslkeytype sslversion tls13_ciphers
          tlsauth_password tlsauth_type tlsauth_username
        ],
        "WS" => %i[
          ws_options
        ],
      }.freeze

      # option => curl value type (LONG STRING SLIST OFF_T OBJECT BLOB CBPTR VALUES FUNCTION)
      TYPES = {
        :abstract_unix_socket => "STRING",
        :accept_encoding => "STRING",
        :accepttimeout_ms => "LONG",
        :address_scope => "LONG",
        :altsvc => "STRING",
        :altsvc_ctrl => "LONG",
        :append => "LONG",
        :autoreferer => "LONG",
        :aws_sigv4 => "STRING",
        :buffersize => "LONG",
        :ca_cache_timeout => "LONG",
        :cainfo => "STRING",
        :cainfo_blob => "BLOB",
        :capath => "STRING",
        :certinfo => "LONG",
        :chunk_bgn_function => "FUNCTION",
        :chunk_data => "CBPTR",
        :chunk_end_function => "FUNCTION",
        :closesocketdata => "CBPTR",
        :closesocketfunction => "FUNCTION",
        :connect_only => "LONG",
        :connect_to => "SLIST",
        :connecttimeout => "LONG",
        :connecttimeout_ms => "LONG",
        :conv_from_network_function => "FUNCTION",
        :conv_from_utf8_function => "FUNCTION",
        :conv_to_network_function => "FUNCTION",
        :cookie => "STRING",
        :cookiefile => "STRING",
        :cookiejar => "STRING",
        :cookielist => "STRING",
        :cookiesession => "LONG",
        :copypostfields => "OBJECT",
        :crlf => "LONG",
        :crlfile => "STRING",
        :curlu => "OBJECT",
        :customrequest => "STRING",
        :debugdata => "CBPTR",
        :debugfunction => "FUNCTION",
        :default_protocol => "STRING",
        :dirlistonly => "LONG",
        :disallow_username_in_url => "LONG",
        :dns_cache_timeout => "LONG",
        :dns_interface => "STRING",
        :dns_local_ip4 => "STRING",
        :dns_local_ip6 => "STRING",
        :dns_servers => "STRING",
        :dns_shuffle_addresses => "LONG",
        :dns_use_global_cache => "LONG",
        :doh_ssl_verifyhost => "LONG",
        :doh_ssl_verifypeer => "LONG",
        :doh_ssl_verifystatus => "LONG",
        :doh_url => "STRING",
        :ech => "STRING",
        :egdsocket => "STRING",
        :errorbuffer => "OBJECT",
        :expect_100_timeout_ms => "LONG",
        :failonerror => "LONG",
        :filetime => "LONG",
        :fnmatch_data => "CBPTR",
        :fnmatch_function => "FUNCTION",
        :followlocation => "LONG",
        :forbid_reuse => "LONG",
        :fresh_connect => "LONG",
        :ftp_account => "STRING",
        :ftp_alternative_to_user => "STRING",
        :ftp_create_missing_dirs => "LONG",
        :ftp_filemethod => "VALUES",
        :ftp_skip_pasv_ip => "LONG",
        :ftp_ssl_ccc => "LONG",
        :ftp_use_eprt => "LONG",
        :ftp_use_epsv => "LONG",
        :ftp_use_pret => "LONG",
        :ftpport => "STRING",
        :ftpsslauth => "VALUES",
        :gssapi_delegation => "VALUES",
        :happy_eyeballs_timeout_ms => "LONG",
        :haproxy_client_ip => "STRING",
        :haproxyprotocol => "LONG",
        :header => "LONG",
        :headerdata => "CBPTR",
        :headerfunction => "FUNCTION",
        :headeropt => "VALUES",
        :hsts => "STRING",
        :hsts_ctrl => "LONG",
        :hstsreaddata => "CBPTR",
        :hstsreadfunction => "FUNCTION",
        :hstswritedata => "CBPTR",
        :hstswritefunction => "FUNCTION",
        :http09_allowed => "LONG",
        :http200aliases => "SLIST",
        :http_content_decoding => "LONG",
        :http_transfer_decoding => "LONG",
        :http_version => "VALUES",
        :httpauth => "VALUES",
        :httpget => "LONG",
        :httpheader => "SLIST",
        :httppost => "OBJECT",
        :httpproxytunnel => "LONG",
        :ignore_content_length => "LONG",
        :infilesize => "LONG",
        :infilesize_large => "OFF_T",
        :interface => "STRING",
        :interleavedata => "CBPTR",
        :interleavefunction => "FUNCTION",
        :ioctldata => "CBPTR",
        :ioctlfunction => "FUNCTION",
        :ipresolve => "VALUES",
        :issuercert => "STRING",
        :issuercert_blob => "BLOB",
        :keep_sending_on_error => "LONG",
        :keypasswd => "STRING",
        :krblevel => "STRING",
        :localport => "LONG",
        :localportrange => "LONG",
        :login_options => "STRING",
        :low_speed_limit => "LONG",
        :low_speed_time => "LONG",
        :mail_auth => "STRING",
        :mail_from => "STRING",
        :mail_rcpt => "SLIST",
        :mail_rcpt_allowfails => "LONG",
        :max_recv_speed_large => "OFF_T",
        :max_send_speed_large => "OFF_T",
        :maxage_conn => "LONG",
        :maxconnects => "LONG",
        :maxfilesize => "LONG",
        :maxfilesize_large => "OFF_T",
        :maxlifetime_conn => "LONG",
        :maxredirs => "LONG",
        :mime_options => "LONG",
        :mimepost => "OBJECT",
        :netrc => "VALUES",
        :netrc_file => "STRING",
        :new_directory_perms => "LONG",
        :new_file_perms => "LONG",
        :nobody => "LONG",
        :noprogress => "LONG",
        :noproxy => "STRING",
        :nosignal => "LONG",
        :opensocketdata => "CBPTR",
        :opensocketfunction => "FUNCTION",
        :password => "STRING",
        :path_as_is => "LONG",
        :pinnedpublickey => "STRING",
        :pipewait => "LONG",
        :port => "LONG",
        :post => "LONG",
        :postfields => "OBJECT",
        :postfieldsize => "LONG",
        :postfieldsize_large => "OFF_T",
        :postquote => "SLIST",
        :postredir => "VALUES",
        :pre_proxy => "STRING",
        :prequote => "SLIST",
        :prereqdata => "CBPTR",
        :prereqfunction => "FUNCTION",
        :private => "OBJECT",
        :progressfunction => "FUNCTION",
        :protocols => "LONG",
        :protocols_str => "STRING",
        :proxy => "STRING",
        :proxy_cainfo => "STRING",
        :proxy_cainfo_blob => "BLOB",
        :proxy_capath => "STRING",
        :proxy_crlfile => "STRING",
        :proxy_issuercert => "STRING",
        :proxy_issuercert_blob => "BLOB",
        :proxy_keypasswd => "STRING",
        :proxy_pinnedpublickey => "STRING",
        :proxy_service_name => "STRING",
        :proxy_ssl_cipher_list => "STRING",
        :proxy_ssl_options => "LONG",
        :proxy_ssl_verifyhost => "LONG",
        :proxy_ssl_verifypeer => "LONG",
        :proxy_sslcert => "STRING",
        :proxy_sslcert_blob => "BLOB",
        :proxy_sslcerttype => "STRING",
        :proxy_sslkey => "STRING",
        :proxy_sslkey_blob => "BLOB",
        :proxy_sslkeytype => "STRING",
        :proxy_sslversion => "VALUES",
        :proxy_tls13_ciphers => "STRING",
        :proxy_tlsauth_password => "STRING",
        :proxy_tlsauth_type => "STRING",
        :proxy_tlsauth_username => "STRING",
        :proxy_transfer_mode => "LONG",
        :proxyauth => "VALUES",
        :proxyheader => "SLIST",
        :proxypassword => "STRING",
        :proxyport => "LONG",
        :proxytype => "VALUES",
        :proxyusername => "STRING",
        :proxyuserpwd => "STRING",
        :put => "LONG",
        :quick_exit => "LONG",
        :quote => "SLIST",
        :random_file => "STRING",
        :range => "STRING",
        :readdata => "CBPTR",
        :readfunction => "FUNCTION",
        :redir_protocols => "LONG",
        :redir_protocols_str => "STRING",
        :referer => "STRING",
        :request_target => "STRING",
        :resolve => "SLIST",
        :resolver_start_data => "CBPTR",
        :resolver_start_function => "FUNCTION",
        :resume_from => "LONG",
        :resume_from_large => "OFF_T",
        :rtsp_client_cseq => "LONG",
        :rtsp_request => "VALUES",
        :rtsp_server_cseq => "LONG",
        :rtsp_session_id => "STRING",
        :rtsp_stream_uri => "STRING",
        :rtsp_transport => "STRING",
        :sasl_authzid => "STRING",
        :sasl_ir => "LONG",
        :seekdata => "CBPTR",
        :seekfunction => "FUNCTION",
        :server_response_timeout => "LONG",
        :server_response_timeout_ms => "LONG",
        :service_name => "STRING",
        :share => "OBJECT",
        :sockoptdata => "CBPTR",
        :sockoptfunction => "FUNCTION",
        :socks5_auth => "LONG",
        :socks5_gssapi_nec => "LONG",
        :socks5_gssapi_service => "STRING",
        :ssh_auth_types => "VALUES",
        :ssh_compression => "LONG",
        :ssh_host_public_key_md5 => "STRING",
        :ssh_host_public_key_sha256 => "STRING",
        :ssh_hostkeydata => "CBPTR",
        :ssh_hostkeyfunction => "FUNCTION",
        :ssh_keydata => "CBPTR",
        :ssh_keyfunction => "FUNCTION",
        :ssh_knownhosts => "STRING",
        :ssh_private_keyfile => "STRING",
        :ssh_public_keyfile => "STRING",
        :ssl_cipher_list => "STRING",
        :ssl_ctx_data => "CBPTR",
        :ssl_ctx_function => "FUNCTION",
        :ssl_ec_curves => "STRING",
        :ssl_enable_alpn => "LONG",
        :ssl_enable_npn => "LONG",
        :ssl_falsestart => "LONG",
        :ssl_options => "VALUES",
        :ssl_sessionid_cache => "LONG",
        :ssl_signature_algorithms => "STRING",
        :ssl_verifyhost => "LONG",
        :ssl_verifypeer => "LONG",
        :ssl_verifystatus => "LONG",
        :sslcert => "STRING",
        :sslcert_blob => "BLOB",
        :sslcerttype => "STRING",
        :sslengine => "STRING",
        :sslengine_default => "LONG",
        :sslkey => "STRING",
        :sslkey_blob => "BLOB",
        :sslkeytype => "STRING",
        :sslversion => "VALUES",
        :stderr => "OBJECT",
        :stream_depends => "OBJECT",
        :stream_depends_e => "OBJECT",
        :stream_weight => "LONG",
        :suppress_connect_headers => "LONG",
        :tcp_fastopen => "LONG",
        :tcp_keepalive => "LONG",
        :tcp_keepcnt => "LONG",
        :tcp_keepidle => "LONG",
        :tcp_keepintvl => "LONG",
        :tcp_nodelay => "LONG",
        :telnetoptions => "SLIST",
        :tftp_blksize => "LONG",
        :tftp_no_options => "LONG",
        :timecondition => "VALUES",
        :timeout => "LONG",
        :timeout_ms => "LONG",
        :timevalue => "LONG",
        :timevalue_large => "OFF_T",
        :tls13_ciphers => "STRING",
        :tlsauth_password => "STRING",
        :tlsauth_type => "STRING",
        :tlsauth_username => "STRING",
        :trailerdata => "CBPTR",
        :trailerfunction => "FUNCTION",
        :transfer_encoding => "LONG",
        :transfertext => "LONG",
        :unix_socket_path => "STRING",
        :unrestricted_auth => "LONG",
        :upkeep_interval_ms => "LONG",
        :upload => "LONG",
        :upload_buffersize => "LONG",
        :upload_flags => "LONG",
        :url => "STRING",
        :use_ssl => "VALUES",
        :useragent => "STRING",
        :username => "STRING",
        :userpwd => "STRING",
        :verbose => "LONG",
        :wildcardmatch => "LONG",
        :writedata => "CBPTR",
        :writefunction => "FUNCTION",
        :ws_options => "LONG",
        :xferinfodata => "CBPTR",
        :xferinfofunction => "FUNCTION",
        :xoauth2_bearer => "STRING",
      }.freeze

      # Documented but absent from curl's setopt table (deprecated/aliased), skipped:
      #   PROGRESSDATA
  end
end
